/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.7/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    eclipse
}

repositories {
    mavenLocal()
    // Use JCenter for resolving dependencies.
    jcenter()
    
    maven(url = "http://www.seis.sc.edu/software/maven2")
}

dependencies {
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.6.2")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // This dependency is used by the application.
        implementation("edu.sc.seis:seedCodec:1.0.11")
    implementation("edu.sc.seis:seisFile:2.0.0-SNAPSHOT") {
      // we need seisFile for sac output, but not all the other functionality
      exclude("com.martiansoftware:jsap")
      exclude("org.rxtx:rxtx")
      exclude("org.codehaus.woodstox:woodstox-core-lgpl")
      exclude("net.java.dev.msv:msv-core")
      exclude("org.apache.httpcomponents:httpclient")
      exclude("mysql:mysql-connector-java")
    }
    implementation("edu.sc.seis:TauP:2.4.5")
    implementation("edu.sc.seis:sod:4.0.0-SNAPSHOT-WEBSTATUS")
    implementation("edu.sc.seis:sod-model:4.0.0-SNAPSHOT")
    implementation("edu.sc.seis:sod-mock:4.0.0-SNAPSHOT")
    implementation("edu.sc.seis:sod-util:4.0.0-SNAPSHOT")
    implementation("edu.sc.seis:sod-bag:4.0.0-SNAPSHOT")
    implementation("com.oregondsp.signalprocessing:oregondsp:1.0.1-alpha")
    implementation("org.json:json:20170516")
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

application {
    // Define the main class for the application.
    mainClass.set("HKStack.App")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
