#!/bin/sh


n="Zhu S. Cal."
m="receiver function"
r="Zhu, L., H. Kanamori, 2000, Moho Depth Variation in Southern California from Teleseismic Receiver Functions, J. Geophys. Res. 105, 2969-2980"
f=importLupei.in
props=ears.prop
u=http://www.eas.slu.edu/People/LZhu/home.html


if [ -z "${JAVA}" ] ; then
JAVA=java
fi
if [ -z "${SOD_HOME}" ]; then
  PRG=$0
  saveddir=`pwd`

  # need this for relative symlinks
  PRGDIR=`dirname "$PRG"`

  SOD_HOME="$PRGDIR/.."

  # make it fully qualified
  SOD_HOME=`cd "${SOD_HOME}" && pwd`

  cd "$saveddir"
fi
LIB=${SOD_HOME}/lib

REV=${LIB}/rev-0.1alpha.jar
JETTY=${LIB}/jetty-4.2.22.jar
SERVLETAPI=${LIB}/servletapi-2.3.jar
CORMORANT=${LIB}/cormorant-0.1beta.jar
COMMONS_CLI=${LIB}/commons-cli-1.0.jar
MULTIVALENT=${LIB}/Multivalent-R7_USC2.jar
GEEMAC=${LIB}/geeMac-1.3.jar
RECFUNCIDL=${LIB}/recFuncIDL-1.0beta.jar
ETOPO10=${LIB}/etopo10.jar
VMAP_PO_THINNED=${LIB}/vmap_po_thinned.jar
POSTGRESQL=${LIB}/postgresql-7.4.1-jdbc3.jar
ISTI_UTIL=${LIB}/isti.util-1.0.1USC.jar
ISTI_UTIL_TOPLEVEL=${LIB}/isti.util.toplevel-1.0USC.jar
JDOM=${LIB}/jdom-b9.jar
GEE=${LIB}/gee-2.1.2beta.jar
SOD=${LIB}/sod-2.0.1beta.jar
JING=${LIB}/jing-20030619.jar
OPENMAP=${LIB}/openmap-4.6.1.jar
JCALENDAR=${LIB}/jcalendar-0.76.jar
JACORB=${LIB}/JacORB-2.1_USC1.jar
IDL=${LIB}/idl-2.1.jar
ANTLR=${LIB}/antlr-2.7.2.jar
AVALON_FRAMEWORK=${LIB}/avalon-framework-4.1.5.jar
CONCURRENT=${LIB}/concurrent-1.3.2.jar
LOGKIT=${LIB}/logkit-1.2.jar
FISSURESUTIL=${LIB}/fissuresUtil-1.0.12beta.jar
FISSURESIMPL=${LIB}/fissuresImpl-1.1.9beta.jar
FISSURESIDL=${LIB}/fissuresIDL-1.0.jar
SEEDCODEC=${LIB}/SeedCodec-1.0beta2.jar
TAUP=${LIB}/TauP-1.1.5beta.jar
MCKOI=${LIB}/mckoi-1.0.2.jar
HSQLDB=${LIB}/hsqldb-1.7.3_USC1.jar
LOG4J=${LIB}/log4j-1.2.8.jar
RNGCONV=${LIB}/rngconv-20030225.jar
MSV=${LIB}/msv-20030807.jar
ISORELAX=${LIB}/isorelax-20030807.jar
RELAXNGDATATYPE=${LIB}/relaxngDatatype-20030807.jar
XSDLIB=${LIB}/xsdlib-20030807.jar
VELOCITY=${LIB}/velocity-1.5-USC1.jar
COMMONS_COLLECTIONS=${LIB}/commons-collections-3.0.jar
VELOCITY_TOOLS_GENERIC=${LIB}/velocity-tools-generic-1.1-rc1.jar
JAX_QNAME=${LIB}/jax-qname-1.0.jar
JSR173_API=${LIB}/jsr173_api-1.0.jar
JSR173_RI=${LIB}/jsr173_ri-1.0.jar
NAMESPACE=${LIB}/namespace-1.0.jar
ITEXT=${LIB}/itext-0.99.jar
RECFUNC=${LIB}/recFunc-1.0beta.jar

CLASSPATH=${REV}:${JETTY}:${SERVLETAPI}:${CORMORANT}:${COMMONS_CLI}:${MULTIVALENT}:${GEEMAC}:${RECFUNCIDL}:${ETOPO10}:${VMAP_PO_THINNED}:${POSTGRESQL}:${ISTI_UTIL}:${ISTI_UTIL_TOPLEVEL}:${JDOM}:${GEE}:${SOD}:${JING}:${OPENMAP}:${JCALENDAR}:${JACORB}:${IDL}:${ANTLR}:${AVALON_FRAMEWORK}:${CONCURRENT}:${LOGKIT}:${FISSURESUTIL}:${FISSURESIMPL}:${FISSURESIDL}:${SEEDCODEC}:${TAUP}:${MCKOI}:${HSQLDB}:${LOG4J}:${RNGCONV}:${MSV}:${ISORELAX}:${RELAXNGDATATYPE}:${XSDLIB}:${VELOCITY}:${COMMONS_COLLECTIONS}:${VELOCITY_TOOLS_GENERIC}:${JAX_QNAME}:${JSR173_API}:${JSR173_RI}:${NAMESPACE}:${ITEXT}:${RECFUNC}


${JAVA} -Xmx556m \
-Dorg.omg.CORBA.ORBSingletonClass=org.jacorb.orb.ORBSingleton \
-Djava.awt.headless=true \
-Dorg.omg.CORBA.ORBClass=org.jacorb.orb.ORB \
-Dswing.volatileImageBufferEnabled=false \
-Djava.endorsed.dirs=:${LIB}/endorsed \
-Djacorb.connection.client.pending_reply_timeout=120000 \
-cp ${CLASSPATH} edu.sc.seis.receiverFunction.compare.JDBCStationResult \
-n "$n" -r "$r" -m "$m" -props "$props" -u "$u" -f "$f"
