
#pragma prefix "seis.sc.edu"

#include "Fissures.idl"
#include "IfTimeSeries.idl"
#include "IfNetwork.idl"
#include "IfEvent.idl"
#include "IfSeismogramDC.idl"

module IfReceiverFunction {

	typedef sequence<Fissures::IfNetwork::Channel> ChannelSeq;
	typedef sequence<Fissures::IfNetwork::ChannelId> ChannelIdSeq;
	
	struct IterDeconConfig {
		float gwidth;
		long maxBumps;
		float tol;
	};
	
    typedef sequence<IterDeconConfig> IterDeconConfigSeq;
	
    interface RecFuncCache {

        boolean isCached(in Fissures::IfEvent::EventAccess event, 
        				    in ChannelIdSeq channel,
        				    in IterDeconConfig config);
        				    
        
        IterDeconConfigSeq getCachedConfigs(in Fissures::IfEvent::EventAccess event, 
        				    in ChannelIdSeq channel);

        Fissures::IfSeismogramDC::LocalSeismogramSeq get(
                           in Fissures::IfEvent::EventAccess event,
                           in ChannelIdSeq channel,
                           in IterDeconConfig config);
					      
        void insert(in Fissures::IfEvent::EventAccess event,
					      in IterDeconConfig config,
					      in ChannelSeq channels,
					      in Fissures::IfSeismogramDC::LocalSeismogramSeq original,
					      in Fissures::IfSeismogramDC::LocalSeismogram radial,
					      in float radialError,
					      in Fissures::IfSeismogramDC::LocalSeismogram tansverse,
					      in float transverseError
                    );

    };
};
